name: Run ESLint on Push

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      # Install Node.js
      - name: Setup Node.js environment
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: v18.17.0

      # Install your dependencies
      - name: Install dependencies
        run: npm ci

      # Run ESLint
      - name: ESLint Check
        uses: eslint/github-action@v0
