name: Prettier Check

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Node.js environment
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: v18.17.0

      - name: Install dependencies
        run: npm ci

      - name: Prettier Check
        run: npx prettier --check .
